name: "ghav before: ⚙️ CI"
"on":
  push:
    branches:
      - ghav/dev/8504
    paths:
      - .ghav/before
env:
  NX_SKIP_NX_CACHE: "true"
jobs:
  only-doc-changes:
    name: 📖 Only doc changes?
    runs-on: ubuntu-latest
    outputs:
      only-doc-changes: "false"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
        working-directory: ./.github/actions/only_doc_changes
  check:
    needs: only-doc-changes
    name: ✅ Check constraints, dependencies, and package.json's
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
        working-directory: ./tasks/check
      - name: ✅ Check constraints, dependencies, and package.json's
        uses: ./tasks/check
  build-lint-test:
    needs: check
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
      fail-fast: true
    name: 🏗 Build, lint, test / ${{ matrix.os }} / node 18 latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Remove the tsc problem matcher if not ubuntu-latest
        if: matrix.os != 'ubuntu-latest'
        run: echo "echo "::remove-matcher owner=tsc::""
      - uses: actions/checkout@v3
      - name: 🧶 Set up job
        uses: ./.github/actions/set-up-job
      - name: 🔨 Build
        run: yarn build
      - name: 🔎 Lint
        run: yarn lint
      - name: Get number of CPU cores
        if: always()
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: 🧪 Test
        run: yarn test-ci ${{ steps.cpu-cores.outputs.count }}
  tutorial-e2e:
    needs: check
    strategy:
      matrix:
        os:
          - ubuntu-latest
      fail-fast: true
    name: 🌲 Tutorial E2E / ${{ matrix.os }} / node 18 latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: 🧶 Set up job
        uses: ./.github/actions/set-up-job
      - name: 📁 Create a temporary directory
        id: createpath
        run: |
          project_path=$(mktemp -d -t redwood.XXXXXX)
          echo "::set-output name=project_path::$project_path"
          framework_path=$(pwd)
          echo "::set-output name=framework_path::$framework_path"
      - name: 🌲 Create a Redwood App
        run: ./tasks/run-e2e ${{ steps.createpath.outputs.project_path }} --no-start
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: 🐙 Git init in the Redwood App directory
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git init --initial-branch main && git add .
          git commit -a --message=init
        working-directory: ${{ steps.createpath.outputs.project_path }}
      - name: Start server in background
        run: yarn rw dev --no-generate --fwd="--no-open" &
        working-directory: ${{ steps.createpath.outputs.project_path }}
      - name: 🌲 Install Cypress
        run: yarn run cypress install
      - name: 🌲 Run cypress
        uses: cypress-io/github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RW_PATH: ${{ steps.createpath.outputs.project_path }}
        with:
          install: false
          env: true
          browser: chrome
          record: false
          wait-on: http://[::1]:8910
          working-directory: ./tasks/e2e
          spec: |
            cypress/e2e/01-tutorial/*.cy.js
            cypress/e2e/04-logger/*.cy.js
  telemetry-check:
    needs: check
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
      fail-fast: true
    name: 🔭 Telemetry check / ${{ matrix.os }} / node 18 latest
    runs-on: ${{ matrix.os }}
    env:
      REDWOOD_REDIRECT_TELEMETRY: http://127.0.0.1:48619
    steps:
      - uses: actions/checkout@v3
      - name: 🧶 Set up job
        uses: ./.github/actions/set-up-job
      - name: 🔨 Build
        run: yarn build
      - name: 📢 Listen for telemetry (CRWA)
        run: node ./.github/actions/telemetry_check/check.mjs --mode crwa
      - name: 📢 Listen for telemetry (CLI)
        run: node ./.github/actions/telemetry_check/check.mjs --mode cli
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
